name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u shalke87 --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/shalke87/blog:latest .

      - name: Push Docker image
        run: docker push ghcr.io/shalke87/blog:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # <-- aggiunge questo

      - name: Copy .env to server and create uploads directory
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # 1. Prepara la directory degli upload
            sudo mkdir -p /var/www/blog/uploads
            sudo chown -R ubuntu:ubuntu /var/www/blog/uploads
            # 2. Crea il file .env con le variabili d'ambiente
            cd ~/projects/blog-BE
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          EOF

      - name: Copy docker-compose.prod.yml to server
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          scp -o StrictHostKeyChecking=no -i key.pem docker-compose.prod.yml \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}/projects/blog-BE/docker-compose.prod.yml
            
      - name: Restart container on server
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd ~/projects/blog-BE
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml up -d
          EOF
